# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Use: `pre-commit autoupdate` to update the hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
# If used jointly with flake8-import-order, ensure that flake8 import order
#   is set to the same style that is enforced by zimports.
#   E.g. add `import-order-style = google` to your .flake8 file.
  - repo: https://github.com/sqlalchemyorg/zimports/
    rev: v0.6.1
    hooks:
      - id: zimports
        args: [ --style=pycharm ]
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args: [ --py36-plus ]
  - repo: https://github.com/pycqa/flake8
    rev: '7.0.0'
    hooks:
      - id: flake8
        exclude: (__pycache__|.venv|tmp|.tox)
        additional_dependencies: [ flake8-import-order ]
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.6
    hooks:
      - id: python-bandit-vulnerability-check
        args: [ -r, --ini, .bandit ]
